apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  labels:
    app: devsecops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
        - name: devsecops-app
          image: DOCKER_IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: CONTAINER_PORT_PLACEHOLDER
          env:
            - name: APP_ENV
              value: APP_ENV_PLACEHOLDER
